export const prompts = [
  "You find a door in your house that wasn't there yesterday.",
  "Write the last conversation between two strangers on a train.",
  "A character discovers they've been living the same Tuesday for years.",
  "The lighthouse keeper receives a message in a bottle — but it's from herself.",
  "Two people meet at the end of the world and argue about something trivial.",
  "Write a scene entirely from the perspective of a dog watching its owner cry.",
  "A cartographer is hired to map a city that doesn't exist yet.",
  "The last library on Earth is about to close. One book can be saved.",
  "Someone wakes up with the ability to hear objects' memories.",
  "Write the moment a character realizes they've been the villain all along.",
  "A letter written to a stranger whose address you found in a used book.",
  "The ocean has been slowly reclaiming the town for decades. Today it takes the post office.",
  "Two siblings find their childhood home listed as 'haunted' on a real estate site.",
  "A musician composes a song that only one person in the world can hear.",
  "Write a scene where the weather perfectly mirrors a character's emotional state — but the character never mentions their feelings.",
  "The interview for a job at a company that may not be entirely human.",
  "A traveler asks for directions in a town where everyone has forgotten their past.",
  "Write the morning routine of someone who knows today is their last ordinary day.",
  "The zoo animals are polite but tired of being watched.",
  "A clock that runs backwards is found in an antique shop. The shopkeeper explains what it's for.",
  "Two ghosts argue about who gets to haunt the attic.",
  "Write about a color that doesn't exist in this world, and someone who can see it.",
  "A gardener discovers that one of her plants is trying to communicate.",
  "The translator at a peace summit realizes she's been given two different versions of the speech.",
  "Write the first five minutes of a party where everyone is pretending to be someone else.",
  "A child asks a question so simple that no adult can answer it honestly.",
  "The last train of the night carries only people with secrets.",
  "Write a goodbye that doesn't use the word 'goodbye'.",
  "An astronaut returns to Earth to find that no one remembers she left.",
  "The museum curator discovers a painting that changes every night.",
  "Write a story where the setting is the most important character.",
  "A rivalry between two bakers in a small town escalates to absurd extremes.",
  "Someone receives a voicemail from themselves — from ten years in the future.",
  "Write the scene where a character finally says the thing they've been holding back for years.",
  "The map says there's a road here. There is no road.",
  "A detective investigates a crime where nothing was stolen — only left behind.",
  "Two people who have never met are both having the same dream.",
  "Write about an inheritance that turns out to be a burden, not a gift.",
  "The town has a rule: no one speaks about what lives in the lake. A newcomer asks.",
  "A chef creates a dish that tastes exactly like a memory.",
  "Write the confession of someone who got away with something small but can't let it go.",
  "The last human and the last robot have a conversation about what the other one is missing.",
  "A woman discovers that her shadow has been doing things she hasn't.",
  "Write about the moment a long friendship begins to crack.",
  "The fortune teller gives a reading that is completely accurate and completely useless.",
  "A bookshop only sells books to customers it deems worthy.",
  "Write a scene from the middle of a war that has nothing to do with fighting.",
  "Someone finds a photograph of themselves in a place they've never been.",
  "The village elder finally agrees to tell the story she has refused to tell for forty years.",
  "Write the last entry in a diary that was never meant to be found.",
  "A child builds a door out of cardboard. When they open it, something is on the other side.",
  "Two neighbors have shared a fence for thirty years. One is finally taking it down.",
  "Write about a kindness so small it went unnoticed — except by the person who needed it most.",
  "The understudy goes on. The audience doesn't know. She does.",
  "A scientist proves something true that everyone wishes were false.",
  "Write a journey where the destination turns out to be less important than expected.",
  "The radio picks up a signal from a ship that sank decades ago.",
  "A character inherits a house full of clocks, all stopped at the same time.",
  "Write the moment someone decides to stay when every instinct says to leave.",
];

export function getRandomPrompt(excludePrompt = null) {
  const available = excludePrompt
    ? prompts.filter(p => p !== excludePrompt)
    : prompts;
  return available[Math.floor(Math.random() * available.length)];
}
